### PR TITLE
Bug Test

### PR DESCRIPTION
**Pull request by Zolix-ai**
This bug test ( unit test ) needs to fail for me to know your circleci is running the tests properly

### CODE REVIEW

**Comment by Zolix-ai** [comment]
@tr-sangale same issue, I guess I didn't sync at first. No difference!

**Comment by Zolix-ai** [comment]
Some time it delays, will just wait and see. It's 3am at my end, API's sleep sometimes :)

**Comment by tr-sangale** [comment]
@Zolix-ai 😂😂, maybe they sleeping

**Comment by tr-sangale** [comment]
image

@Zolix-ai @Redeem-Grimm-Satoshi it's working fine by my side and i tested it with another github account, the pipeline works after merging the PR,( and not when we initiate a PR) and on the other hand `suitcase`  pipeline runs fine on initiating a PR, 
and surprisingly i have the same settings for both the pipelines

**Comment by tr-sangale** [comment]
@Zolix-ai @Redeem-Grimm-Satoshi made some changes to config file, please sync fork and try again

**Comment by tr-sangale** [comment]
Hi @Redeem-Grimm-Satoshi @Zolix-ai , surprisingly the bug which you are trying to test won't make the pipeline to fail(i tried that , and also deleted the whole file `PropertiesNonPrivilegedTest.java` , to see if the pipeline fails, but it did not), I don't know why that is happening, but on the other hand when i tried to plant the bug in `androidlibrary/androidlibrary_lib/src/test/java/org/opendatakit` instead of planting it in `androidlibrary/androidlibrary_lib/src/androidTest`, the pipeline failed the tests

so please look into it

**Comment by Zolix-ai** [comment]
send link to the pipline

**Comment by tr-sangale** [comment]
https://app.circleci.com/pipelines/github/tr-sangale/androidlibrary

you mean this right?

**Comment by Zolix-ai** [comment]
show me the pipeline where PropertiesNonPrivilegedTest.java failed the test

**Comment by tr-sangale** [comment]
no, I'm saying that changes in PropertiesNonPrivilegedTest.java , won't fail the test, i removed the whole file in this pipeline https://app.circleci.com/pipelines/github/tr-sangale/androidlibrary/97/workflows/03fc4b99-603c-4072-ab91-c5b925516fec
but still the test didn't fail

**Comment by tr-sangale** [comment]
whereas on the other hand if i make a change in one of the files from `androidlibrary/androidlibrary_lib/src/test/java/org/opendatakit`

the tests will fail

**Comment by tr-sangale** [comment]
image
in this pipeline i've deleted the whole file PropertiesNonPrivilegedTest.java , but still the tests didn't fail

**Comment by Zolix-ai** [comment]
You don't create your own test! 

Do you understand?

**Comment by tr-sangale** [comment]
okay !
yes

**Comment by Zolix-ai** [comment]
the main objective is;

1. make sure circleci is running the test properly ( if it's running properly, that should fail! )

We don't provide issues we haven't tested ourselves. The main is for you to understand how things work :)

**Comment by tr-sangale** [comment]
yeah !

**Comment by tr-sangale** [comment]
will you please, sync the fork and check once, so that i can revise the pipeline , if it is not giving desired output
thankyou for your feedback !

**Pull request closed without merging**
