### PR TITLE
Bug Test

### PR DESCRIPTION
**Pull request by Zolix-ai**
Verify if CircleCI is testing properly

### CODE REVIEW

**Comment by tr-sangale** [comment]
hey @Zolix-ai @Redeem-Grimm-Satoshi , i changed my config file, but i'm getting a error, will you please help me with it or give some clue of how to solve it 
>`Execution failed for task ':androidlibrary_lib:connectedDemoBasicDebugAndroidTest'.
> com.android.builder.testing.api.DeviceException: No connected devices!`

**Comment by tr-sangale** [comment]
@Redeem-Grimm-Satoshi @Zolix-ai i've committed in the repo , will you please sync fork and check the pipeline

thankyou for your feedback !

**Comment by tr-sangale** [comment]
hey @Redeem-Grimm-Satoshi @Zolix-ai I'm waiting for you to hit a PR, so that if the pipeline does'nt  give the desired output i can modify it further.
Thankyou !

**Comment by Redeem-Grimm-Satoshi** [comment]
@tr-sangale I've checked your config file you aren't running the required tests

`./gradlew test` is vague

**Comment by Redeem-Grimm-Satoshi** [comment]
the docs has what you need: https://docs.odk-x.org/

**Comment by tr-sangale** [comment]
Hey @Redeem-Grimm-Satoshi goodmorning, i guess you haven't sync the fork, because I'm running `./gradlew connectedAndroidTest` also for the ui tests

**Comment by tr-sangale** [comment]
Afternoon @Redeem-Grimm-Satoshi @Zolix-ai , I'm sure that this time the bug test will make the tests in the pipeline to fail, please hit a PR and give it a check.

`And also sync the fork before that`

**Comment by tr-sangale** [comment]
Afternoon @Redeem-Grimm-Satoshi @Zolix-ai , I'm sure that this time the bug test will make the tests in the pipeline to fail, please hit a PR and give it a check.

`And also sync the fork before that`

**Pull request closed without merging**
