### PR TITLE
Bug Test

### PR DESCRIPTION
**Pull request by Zolix-ai**
Verify Bug Test ( this test has to fail )

### CODE REVIEW

**Comment by Zolix-ai** [comment]
@tr-sangale CircleCI not initiatiating issues, try to fix it

**Comment by tr-sangale** [comment]
@Zolix-ai did some changes, you can check now

**Comment by tr-sangale** [comment]
@Redeem-Grimm-Satoshi @Zolix-ai did some changes, you can check now

**Comment by Zolix-ai** [comment]
Make sure it works from forked repos too

**Pull request closed without merging**
